// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmxl_B3sK7dbQHtqM-_o_vexOVY6Wkelc',
    appId: '1:69522046073:android:8d9f96361b162f3eaaa8a8',
    messagingSenderId: '69522046073',
    projectId: 'life-calendar-2ad86',
    storageBucket: 'life-calendar-2ad86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHtOgXiwH_yNAKq-by2IAXgzw3wMjNlDM',
    appId: '1:69522046073:ios:09adb4e917415890aaa8a8',
    messagingSenderId: '69522046073',
    projectId: 'life-calendar-2ad86',
    storageBucket: 'life-calendar-2ad86.firebasestorage.app',
    androidClientId:
        '69522046073-n9ng5sanjlgg0u1tgv2fo65o29ked59v.apps.googleusercontent.com',
    iosClientId:
        '69522046073-5hqveh89rcd6ck3tf2chlcacomvv1dj1.apps.googleusercontent.com',
    iosBundleId: 'com.vgol.lifeCalendar2',
  );
}
